# Etapa de desarrollo
FROM node:14-alpine

WORKDIR /app

# Instalar las dependencias necesarias para el desarrollo
COPY package.json .
COPY yarn.lock .
RUN yarn install

# Copiar los archivos de código
COPY . .

# Exponer el puerto de desarrollo
EXPOSE 5000

# Usar el comando start:dev que ya está definido en package.json
CMD ["yarn", "start:dev"]
